# Generated by Django 4.2.2 on 2023-07-03 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('country', models.CharField(blank=True, choices=[('NG', 'Nigeria'), ('GH', 'Ghana'), ('EG', 'Egypt'), ('ZA', 'South Africa'), ('ET', 'Ethiopia'), ('DZ', 'Algeria'), ('CN', 'China'), ('IN', 'India'), ('JP', 'Japan'), ('VN', 'Vietnam'), ('TH', 'Thailand'), ('KR', 'South Korea'), ('RU', 'Russia'), ('DE', 'Germany'), ('FR', 'France'), ('GB', 'United Kingdom'), ('IT', 'Italy'), ('ES', 'Spain'), ('PL', 'Poland'), ('NL', 'Netherlands'), ('BE', 'Belgium'), ('SE', 'Sweden'), ('US', 'United States'), ('CA', 'Canada'), ('MX', 'Mexico'), ('AU', 'Australia'), ('NZ', 'New Zealand'), ('FJ', 'Fiji'), ('PG', 'Papua New Guinea'), ('BR', 'Brazil'), ('AR', 'Argentina'), ('CO', 'Colombia'), ('PE', 'Peru'), ('CL', 'Chile'), ('VE', 'Venezuela'), ('EC', 'Ecuador'), ('BO', 'Bolivia'), ('PY', 'Paraguay'), ('UY', 'Uruguay')], max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=200, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.order')),
            ],
            options={
                'verbose_name': 'shipping address',
                'verbose_name_plural': 'shipping addresses',
            },
        ),
    ]
